name = "Zlib_jll"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+14"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
